package com.example.postmanapi.model

data class Data(
    val api_master_id: String,
    val api_name: String,
    val btn_color: String,
    val btn_text_color: String,
    val company_id: String,
    val company_name: String,
    val created: String,
    val created_by: String,
    val end_time: Any,
    val form_id: String,
    val id: String,
    val latitude: String,
    val longitude: String,
    val page_url: String,
    val quiz_id: String,
    val quiz_launch: String,
    val quiz_title: String,
    val radius: String,
    val sequence: String,
    val start_time: Any,
    val static_ad: String,
    val status: String,
    val tab_group_id: String,
    val time_slot_id: String,
    val timer: String,
    val title: String,
    val type: String,
    val url_id: String,
    val video: String,
    val video_360: String,
    val video_bar_hide: String,
    val video_present: String,
    val zone_id: String
)